name: pass-authz Continuous Integration
on: [ pull_request, workflow_dispatch ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  call-workaround:
    name: Run Parent POM Workaround
    uses: eclipse-pass/pass-authz/.github/workflows/parent-pom-workaround.yml@main

  call-tests-unit:
    name: Run Unit Tests
    uses: eclipse-pass/pass-authz/.github/workflows/tests-unit.yml@main
    needs: call-workaround

  call-tests-integration:
    name: Run Integration Tests
    uses: eclipse-pass/pass-authz/.github/workflows/tests-integration.yml@main
    needs: call-workaround
